//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("TransmissionHeader", Namespace="", IsNullable=false)]
public partial class TransmissionHeaderType {
    
    private string transmissionIdField;
    
    private System.DateTime timestampField;
    
    private bool timestampFieldSpecified;
    
    private TransmissionHeaderTypeTransmitter transmitterField;
    
    private TransmissionHeaderTypeProcessType processTypeField;
    
    private string documentCountField;
    
    private AmountType transmissionPaymentHashField;
    
    /// <remarks/>
    public string TransmissionId {
        get {
            return this.transmissionIdField;
        }
        set {
            this.transmissionIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TimestampSpecified {
        get {
            return this.timestampFieldSpecified;
        }
        set {
            this.timestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public TransmissionHeaderTypeTransmitter Transmitter {
        get {
            return this.transmitterField;
        }
        set {
            this.transmitterField = value;
        }
    }
    
    /// <remarks/>
    public TransmissionHeaderTypeProcessType ProcessType {
        get {
            return this.processTypeField;
        }
        set {
            this.processTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string DocumentCount {
        get {
            return this.documentCountField;
        }
        set {
            this.documentCountField = value;
        }
    }
    
    /// <remarks/>
    public AmountType TransmissionPaymentHash {
        get {
            return this.transmissionPaymentHashField;
        }
        set {
            this.transmissionPaymentHashField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TransmissionHeaderTypeTransmitter {
    
    private string eTINField;
    
    /// <remarks/>
    public string ETIN {
        get {
            return this.eTINField;
        }
        set {
            this.eTINField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AmountType {
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum TransmissionHeaderTypeProcessType {
    
    /// <remarks/>
    T,
    
    /// <remarks/>
    P,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("AcknowledgementHeader", Namespace="", IsNullable=false)]
public partial class AcknowledgementHeaderType {
    
    private System.DateTime acknowledgementTimestampField;
    
    private string acknowledgementCountField;
    
    /// <remarks/>
    public System.DateTime AcknowledgementTimestamp {
        get {
            return this.acknowledgementTimestampField;
        }
        set {
            this.acknowledgementTimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string AcknowledgementCount {
        get {
            return this.acknowledgementCountField;
        }
        set {
            this.acknowledgementCountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("TransmissionAcknowledgement", Namespace="", IsNullable=false)]
public partial class TransmissionAcknowledgementType {
    
    private string transmissionIdField;
    
    private System.DateTime transmissionTimestampField;
    
    private bool transmissionTimestampFieldSpecified;
    
    private StatusType transmissionStatusField;
    
    private Errors errorsField;
    
    /// <remarks/>
    public string TransmissionId {
        get {
            return this.transmissionIdField;
        }
        set {
            this.transmissionIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TransmissionTimestamp {
        get {
            return this.transmissionTimestampField;
        }
        set {
            this.transmissionTimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TransmissionTimestampSpecified {
        get {
            return this.transmissionTimestampFieldSpecified;
        }
        set {
            this.transmissionTimestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public StatusType TransmissionStatus {
        get {
            return this.transmissionStatusField;
        }
        set {
            this.transmissionStatusField = value;
        }
    }
    
    /// <remarks/>
    public Errors Errors {
        get {
            return this.errorsField;
        }
        set {
            this.errorsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
public enum StatusType {
    
    /// <remarks/>
    A,
    
    /// <remarks/>
    R,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Errors {
    
    private ErrorsError[] errorField;
    
    private string errorCountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Error")]
    public ErrorsError[] Error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string errorCount {
        get {
            return this.errorCountField;
        }
        set {
            this.errorCountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ErrorsError {
    
    private string itemField;
    
    private ItemChoiceType itemElementNameField;
    
    private string errorMessageField;
    
    private string additionalErrorMessageField;
    
    private string severityField;
    
    private string dataValueField;
    
    private string errorIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FieldIdentifier", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("XPath", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
    
    /// <remarks/>
    public string ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
    
    /// <remarks/>
    public string AdditionalErrorMessage {
        get {
            return this.additionalErrorMessageField;
        }
        set {
            this.additionalErrorMessageField = value;
        }
    }
    
    /// <remarks/>
    public string Severity {
        get {
            return this.severityField;
        }
        set {
            this.severityField = value;
        }
    }
    
    /// <remarks/>
    public string DataValue {
        get {
            return this.dataValueField;
        }
        set {
            this.dataValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string errorId {
        get {
            return this.errorIdField;
        }
        set {
            this.errorIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemChoiceType {
    
    /// <remarks/>
    FieldIdentifier,
    
    /// <remarks/>
    XPath,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("DocumentAcknowledgement", Namespace="", IsNullable=false)]
public partial class DocumentAcknowledgementType {
    
    private string documentIdField;
    
    private string itemField;
    
    private ItemChoiceType1 itemElementNameField;
    
    private DocumentAcknowledgementTypeDocumentType documentTypeField;
    
    private StatusType documentStatusField;
    
    private PaymentIndicatorType paymentIndicatorField;
    
    private Errors errorsField;
    
    /// <remarks/>
    public string DocumentId {
        get {
            return this.documentIdField;
        }
        set {
            this.documentIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SSTPID", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("StateID", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType1 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
    
    /// <remarks/>
    public DocumentAcknowledgementTypeDocumentType DocumentType {
        get {
            return this.documentTypeField;
        }
        set {
            this.documentTypeField = value;
        }
    }
    
    /// <remarks/>
    public StatusType DocumentStatus {
        get {
            return this.documentStatusField;
        }
        set {
            this.documentStatusField = value;
        }
    }
    
    /// <remarks/>
    public PaymentIndicatorType PaymentIndicator {
        get {
            return this.paymentIndicatorField;
        }
        set {
            this.paymentIndicatorField = value;
        }
    }
    
    /// <remarks/>
    public Errors Errors {
        get {
            return this.errorsField;
        }
        set {
            this.errorsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemChoiceType1 {
    
    /// <remarks/>
    SSTPID,
    
    /// <remarks/>
    StateID,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum DocumentAcknowledgementTypeDocumentType {
    
    /// <remarks/>
    SSTPRegistration,
    
    /// <remarks/>
    SERWithPayment,
    
    /// <remarks/>
    SEROnly,
    
    /// <remarks/>
    PaymentOnly,
    
    /// <remarks/>
    PrePayment,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
public enum PaymentIndicatorType {
    
    /// <remarks/>
    A,
    
    /// <remarks/>
    R,
    
    /// <remarks/>
    N,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("BulkRegAcknowledgement", Namespace="", IsNullable=false)]
public partial class BulkRegAcknowledgementType {
    
    private string documentIdField;
    
    private string sSTPIDField;
    
    private string newPassField;
    
    private BulkRegAcknowledgementTypeDocumentType documentTypeField;
    
    private StatusType documentStatusField;
    
    private Errors errorsField;
    
    private string documentVersionField;
    
    public BulkRegAcknowledgementType() {
        this.documentVersionField = "SST2015V01";
    }
    
    /// <remarks/>
    public string DocumentId {
        get {
            return this.documentIdField;
        }
        set {
            this.documentIdField = value;
        }
    }
    
    /// <remarks/>
    public string SSTPID {
        get {
            return this.sSTPIDField;
        }
        set {
            this.sSTPIDField = value;
        }
    }
    
    /// <remarks/>
    public string NewPass {
        get {
            return this.newPassField;
        }
        set {
            this.newPassField = value;
        }
    }
    
    /// <remarks/>
    public BulkRegAcknowledgementTypeDocumentType DocumentType {
        get {
            return this.documentTypeField;
        }
        set {
            this.documentTypeField = value;
        }
    }
    
    /// <remarks/>
    public StatusType DocumentStatus {
        get {
            return this.documentStatusField;
        }
        set {
            this.documentStatusField = value;
        }
    }
    
    /// <remarks/>
    public Errors Errors {
        get {
            return this.errorsField;
        }
        set {
            this.errorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string documentVersion {
        get {
            return this.documentVersionField;
        }
        set {
            this.documentVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum BulkRegAcknowledgementTypeDocumentType {
    
    /// <remarks/>
    BulkRegNew,
    
    /// <remarks/>
    BulkRegCOU,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("BulkRegistrationAcknowledgement", Namespace="", IsNullable=false)]
public partial class BulkRegistrationAcknowledgementType {
    
    private AcknowledgementHeaderType acknowledgementHeaderField;
    
    private TransmissionAcknowledgementType transmissionAcknowledgementField;
    
    private BulkRegAcknowledgementType[] bulkRegAcknowledgementField;
    
    private string acknowledgementVersionField;
    
    public BulkRegistrationAcknowledgementType() {
        this.acknowledgementVersionField = "SST2015V01";
    }
    
    /// <remarks/>
    public AcknowledgementHeaderType AcknowledgementHeader {
        get {
            return this.acknowledgementHeaderField;
        }
        set {
            this.acknowledgementHeaderField = value;
        }
    }
    
    /// <remarks/>
    public TransmissionAcknowledgementType TransmissionAcknowledgement {
        get {
            return this.transmissionAcknowledgementField;
        }
        set {
            this.transmissionAcknowledgementField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BulkRegAcknowledgement")]
    public BulkRegAcknowledgementType[] BulkRegAcknowledgement {
        get {
            return this.bulkRegAcknowledgementField;
        }
        set {
            this.bulkRegAcknowledgementField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string acknowledgementVersion {
        get {
            return this.acknowledgementVersionField;
        }
        set {
            this.acknowledgementVersionField = value;
        }
    }
}
